export const GAME_TEXT_LIST = {
  long: [
    [
      "1Round - 1번 - 긴 문구",
      "1Round - 2번 - 긴 문구",
      "1Round - 3번 - 긴 문구",
      "1Round - 4번 - 긴 문구",
      "1Round - 5번 - 긴 문구",
      "1Round - 6번 - 긴 문구",
      "1Round - 7번 - 긴 문구",
      "1Round - 8번 - 긴 문구",
      "1Round - 9번 - 긴 문구",
      "1Round - 10번 - 긴 문구",
    ],
    [
      "2Round - 1번 - 긴 문구",
      "2Round - 2번 - 긴 문구",
      "2Round - 3번 - 긴 문구",
      "2Round - 4번 - 긴 문구",
      "2Round - 5번 - 긴 문구",
      "2Round - 6번 - 긴 문구",
      "2Round - 7번 - 긴 문구",
      "2Round - 8번 - 긴 문구",
      "2Round - 9번 - 긴 문구",
      "2Round - 10번 - 긴 문구",
    ],
    [
      "3Round - 1번 - 긴 문구",
      "3Round - 2번 - 긴 문구",
      "3Round - 3번 - 긴 문구",
      "3Round - 4번 - 긴 문구",
      "3Round - 5번 - 긴 문구",
      "3Round - 6번 - 긴 문구",
      "3Round - 7번 - 긴 문구",
      "3Round - 8번 - 긴 문구",
      "3Round - 9번 - 긴 문구",
      "3Round - 10번 - 긴 문구",
    ],
  ],
  short: [
    [
      "1Round - 1번 - 짧은 단어",
      "1Round - 2번 - 짧은 단어",
      "1Round - 3번 - 짧은 단어",
      "1Round - 4번 - 짧은 단어",
      "1Round - 5번 - 짧은 단어",
      "1Round - 6번 - 짧은 단어",
      "1Round - 7번 - 짧은 단어",
      "1Round - 8번 - 짧은 단어",
      "1Round - 9번 - 짧은 단어",
      "1Round - 10번 - 짧은 단어",
    ],
    [
      "2Round - 1번 - 짧은 단어",
      "2Round - 2번 - 짧은 단어",
      "2Round - 3번 - 짧은 단어",
      "2Round - 4번 - 짧은 단어",
      "2Round - 5번 - 짧은 단어",
      "2Round - 6번 - 짧은 단어",
      "2Round - 7번 - 짧은 단어",
      "2Round - 8번 - 짧은 단어",
      "2Round - 9번 - 짧은 단어",
      "2Round - 10번 - 짧은 단어",
    ],
    [
      "3Round - 1번 - 짧은 단어",
      "3Round - 2번 - 짧은 단어",
      "3Round - 3번 - 짧은 단어",
      "3Round - 4번 - 짧은 단어",
      "3Round - 5번 - 짧은 단어",
      "3Round - 6번 - 짧은 단어",
      "3Round - 7번 - 짧은 단어",
      "3Round - 8번 - 짧은 단어",
      "3Round - 9번 - 짧은 단어",
      "3Round - 10번 - 짧은 단어",
    ],
  ],
};
